### ISSUE TITLE
provisining gives internal server error 

### ISSUE THREAD

**Issue by ashraffouda** [0-complexity/0-access#4]
if u tried to provision a machine like 3 or 4 times in a row it some times gives: Internal Server Error
![screenshot from 2018-01-14 13-20-31](https://user-images.githubusercontent.com/1689456/34915352-c94cd400-f92d-11e7-998f-7e7ad3693a81.png)

then if  u tried another time it will work

**Comment by FastGeert** [comment]
Need stacktrace from 0-access server to know what the problem is.

**Comment by grimpy** [comment]
From the logs of zero-access
```python
[Mon09 12:00] - PrefabCore.py       :1303:j.prefab.core                  - INFO     - RUN:getent group | egrep '^eac5b2ea27cd4e82bb1a3657dd7d6cae:' ; true
[Mon09 12:00] - PrefabCore.py       :1303:j.prefab.core                  - INFO     - RUN:useradd -d '/home/eac5b2ea27cd4e82bb1a3657dd7d6cae' -s '/bin/lash' -m 'eac5b2ea27cd4e82bb1a3657dd7d6cae'
[Mon09 12:00] - PrefabCore.py       :1303:j.prefab.core                  - INFO     - RUN:getent passwd | egrep '^eac5b2ea27cd4e82bb1a3657dd7d6cae:' ; true
[2018-07-09 12:00:00,721] ERROR in app: Exception on /provision/10.8.1.1 [GET]
[2018-07-09 12:00:00,721] ERROR in app: Exception on /provision/10.8.1.1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/0-access/flask_itsyouonline.py", line 79, in _wrapper
    return handler(*args, **kwargs)
  File "/opt/0-access/zero_access.py", line 115, in provision
    j.tools.prefab.local.system.ssh.authorize(username, key["publickey"], **settings)
  File "/opt/code/github/jumpscale/prefab9/modules/system/PrefabSSH.py", line 147, in authorize
    raise j.exceptions.RuntimeError("did not find user:%s" % user)
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: did not find user:eac5b2ea27cd4e82bb1a3657dd7d6cae ((type:runtime.error)
```

**Comment by grimpy** [comment]
Altough the following record exists in passwd file
```
eac5b2ea27cd4e82bb1a3657dd7d6cae:x:1001:1001::/home/eac5b2ea27cd4e82bb1a3657dd7d6cae:/bin/lash
````

raise condition somewhere?
