### ISSUE TITLE
provision should return bad request if there is no public key for the user

### ISSUE THREAD

**Issue by islamTaha12** [0-complexity/0-access#7]
**Description**
In case of ITY user doesn't configure a public key for the organization, provision won't create .ssh directory and it will copy the private key to /home/{user}/.ssh file.

**Expected result**
In case of there is no public keys, it should return bad request or whatever and it should be before creating the tmp user.
https://github.com/0-complexity/0-access/blob/master/0-access.py#L115

**Comment by ashraffouda** [comment]
can not reproduce this

**Comment by ahmedelsayed-93** [comment]
```
Traceback (most recent call last):
~   File "/opt/jumpscale7/lib/JumpScale/portal/portal/PortalRest.py", line 254, in execute_rest_call
    result = method(ctx=ctx, **ctx.params)
~   File "/opt/jumpscale7/apps/portals/main/base/cloudbroker__zeroaccess/methodclass/cloudbroker_zeroaccess.py", line 89, in provision
    return self._zero_access_request(kwargs['ctx'], '{0}/provision/{1}'.format(self.zeroaccessurl, remote))
~   File "/opt/jumpscale7/apps/portals/main/base/cloudbroker__zeroaccess/methodclass/cloudbroker_zeroaccess.py", line 78, in _zero_access_request
    jwt = self._get_jwt(ctx)
~   File "/opt/jumpscale7/apps/portals/main/base/cloudbroker__zeroaccess/methodclass/cloudbroker_zeroaccess.py", line 19, in _get_jwt
    return self.iyoinstance.get_active_jwt(session=ctx.env['beaker.session'])
~   File "/opt/jumpscale7/lib/JumpScale/baselib/oauth/OauthInstance.py", line 135, in get_active_jwt
    jwt_data = jose_jwt.get_unverified_claims(jwt)
~   File "/opt/jumpscale7/lib/jose/jwt.py", line 185, in get_unverified_claims
    raise JWTError('Error decoding token claims.')
~ JWTError: Error decoding token claims.

```

**Comment by ashraffouda** [comment]
this is not related to the issue, 
ur issue is in decoding jwt, may be cause u removed the shared info
the issue for this ticket is 
```
Description
In case of ITY user doesn't configure a public key for the organization, provision won't create .ssh directory and it will copy the private key to /home/{user}/.ssh file.
``` 
check the first two lines in the issue
